site_name: RiWiki
site_url: https://rivzor.github.io/my-wiki/
site_author: rivzor
site_description: Личная база знаний о всём, что связанно с ПК


theme:
  name: material
  language: ru
  custom_dir: docs/overrides/

  palette:
    # Темная тема
    - scheme: slate
      toggle:
        icon: fontawesome/solid/toggle-on
        name: Light mode
      primary: custom
      accent: custom

    # Светлая тема
    - scheme: default
      toggle:
        icon: fontawesome/solid/toggle-off
        name: Dark mode
      primary: custom
      accent: custom

  # Шрифты    
  font:
    text: Inter
    code: JetBrains Mono

  # Логотип / Иконка
  icon:
    logo: material/alien
    
    tag:
      win: fontawesome/brands/windows

  favicon: assets/imgs/pine-tree-variant-outline.svg

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - navigation.expand
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate


nav:
  - Главная: index.md

  - Всё о Windows: 
    - guides/windows/index.md
    - Установка Винды: guides/windows/install.md
    - Скачать Windows/Office: guides/windows/download_iso.md
    - Активировать: guides/windows/activation.md
    - Оптимизация: 
      - Базовая оптимизация: guides/windows/optimization.md
      - Файл автоответов: guides/windows/autounattend.md

  - Гайды:
    # - guides/hacks/index.md
    - Правильный AdBlock в браузерах: guides/hacks/adblock.md

  - Программы:
    # - guides/software/index.md
    - Топ-10 полезных:
      - Rufus: guides/software/top10/rufus.md


plugins:
  - search
  - tags
  - glightbox
  - meta
  

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html

extra_css:
  - stylesheets/extra.css

extra:
  consent:
    title: Согласие на Куки
    description: >- 
      Мы используем файлы cookie, чтобы узнавать ваши повторные визиты и предпочтения, 
      а также чтобы оценивать эффективность нашей документации и выяснять, находят ли пользователи то, что ищут. 
      С вашего согласия вы помогаете нам делать нашу документацию лучше.
  
  tags:
    windows: win

  generator: false
  social:
    - icon: simple/github 
      link: https://github.com/rivzor
    - icon: simple/telegram
      link: https://t.me/rivzor
    - icon: simple/maildotru
      link: mailto:i@rivzor.ru


# copyright: Copyright &copy; 2025 rivzor

watch:
  - docs/